### ISSUE TITLE
Possible to run from R? ;)

### ISSUE THREAD

**Issue by hrj21** [saeyslab/ViVAE#1]
Hi folks,

ViVAE looks really exciting, so congratulations! This isn't really an issue, just a question really. I know ViVAE relies on PyTorch, but I wondered if it's possible to run it in R, perhaps with reticulate? If so, would a simple tutorial be possible for those of us not so familiar with python/anaconda environments? Making ViVAE accessible to the R community would be wonderful!

Thanks and keep innovating.
Hefin

**Comment by davnovak** [comment]
Dear Hefin,

thank you! I am pinning this and will try and provide that tutorial when I find a bit of time for it.

Best regards,
David

**Comment by davnovak** [comment]
Hi Hefin,

I just uploaded a vignette with instructions on installing and using ViVAE in R (see link in README). It's an RMarkdown file that you can open in RStudio.

The tutorial is not as complete as the ones we have for Python, but it's a start. Eventually, we should provide an R package that is independent of Python.

Hope this helps!
Best,

David

**Comment by hrj21** [comment]
Outstanding! I really appreciate you taking the time to do this (reticulate really is quite powerful). This works well for me, the only thing I needed to change was the version of pytorch to 2.1.0 as 2.1.2 wasn't available for some reason. An eventual R package would be wonderful, but this is good for now!  Thanks again :raised_hands:
